{
 "title": "Reader/Writer application Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Writer app metrics", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "# Writer app metrics" },
  {
   "title": "Insert query request time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "insert_query_duration_sum / insert_query_duration_count"
    }
   ]
  },
  {
   "title": "0.25 quantile",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 2 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.25, insert_query_duration_bucket)"
    }
   ]
  },
  {
   "title": "0.5 quantile",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 2 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.5, insert_query_duration_bucket)"
    }
   ]
  },
  {
   "title": "0.75 quantile",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 6 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.75, insert_query_duration_bucket)"
    }
   ]
  },
  {
   "title": "0.95 quantile",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 6 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, insert_query_duration_bucket)"
    }
   ]
  },
  { "title": "Reader app metrics", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 }, "content": "# Reader app metrics" },
  {
   "title": "Count query request time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "count_query_duration_sum / count_query_duration_count"
    }
   ]
  },
  {
   "title": "0.25 quantile",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 13 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.25, count_query_duration_bucket)"
    }
   ]
  },
  {
   "title": "0.5 quantile",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 13 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.5, count_query_duration_bucket)"
    }
   ]
  },
  {
   "title": "0.75 quantile",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 17 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.75, count_query_duration_bucket)"
    }
   ]
  },
  {
   "title": "0.95 quantile",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 17 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, count_query_duration_bucket)"
    }
   ]
  }
 ]
}