apiVersion: v1
kind: Service
metadata:
  name: mysql-master-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: mysql-master
  ports:
    - port: 3306
      targetPort: 3306
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-master-pv-claim
  labels:
    component: mysql-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: mysql-master
  labels:
    component: mysql-master
spec:
  containers:
    - name: master
      image: mysql/master:0.1
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-master-persistent-storage
          mountPath: /var/lib/mysql
          subPath: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: PASS
        - name: MYSQL_REPLICATION_USER
          value: 'demo'
        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-replication-password
              key: PASS
  volumes:
    - name: mysql-master-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-master-pv-claim