apiVersion: v1
kind: Service
metadata:
  name: mysql-slave-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: mysql-slave
  ports:
    - port: 3306
      targetPort: 3306
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-slave-pv-claim
  labels:
    component: mysql-slave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: mysql-slave
  labels:
    component: mysql-slave
spec:
  containers:
    - name: slave
      image: mysql/slave:0.1
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-slave-persistent-storage
          mountPath: /var/lib/mysql
          subPath: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: PASS
        - name: MYSQL_REPLICATION_USER
          value: 'demo'
        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-replication-password
              key: PASS
        - name: MYSQL_MASTER_SERVICE_HOST
          value: mysql-master-cluster-ip
  volumes:
    - name: mysql-slave-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-slave-pv-claim